tournois/tournaments/urls.py
from django.urls import path

from . import views

app_name = 'tournaments'

urlpatterns = [
    # ex: /tournaments/
    path('', views.tournaments_list, name='tournaments_list'),

    # ex: /tournaments/5/
    path('<int:tournament_id>/', views.tournament_details, name='tournament_details'),

    # ex: /tournaments/pool/5
    path('pool/<int:pool_id>/', views.pool_details, name='pool_details'),

    # ex: /tournaments/pool/5/compute_matches
    path('pool/<int:pool_id>/<int:compute_matches>/', views.compute_matches, name='compute_matches'),

    # ex: /tournaments/match/5
    path('match/<int:match_id>/', views.match_details, name='match_details'),
    
    # ex: /tournaments/match_finals/5
    path('match_finals/<int:match_id>/', views.match_details_finals, name='match_details_finals'),

    # ex: /tournaments/match/5/11
    path('match/<int:match_id>/<int:comment_id>/', views.update_comment, name='update_comment'),
        
    # ex: /tournaments/match_finals/5/11
    path('match_finals/<int:match_id>/<int:comment_id>/', views.update_comment_finals, name='update_comment_finals'),
    
    #ex : /tournaments/1/final_round
    path('<int:tournament_id>/final_round/', views.final_round, name='final_round'),
    
    #ex : /tournaments/pool/1/scatter_plot
    path('pool/<int:pool_id>/scatter_plot/', views.scatter_plot, name='scatter_plot'),
    
    path('pool/<int:pool_id>/goals_per_team_plot/', views.goals_per_team_plot, name='goals_per_team_plot'),
    
    path('pool/<int:pool_id>/goals_per_match_plot/', views.goals_per_match_plot, name='goals_per_match_plot'),

    # ex: /tournaments/research
    path('research/', views.research, name='research'),

]

tournois/tournois/urls.py
from django.contrib import admin
from django.urls import include, path

from tournaments import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tournaments/', include('tournaments.urls')),

    # authentication route
    path('accounts/', include('django.contrib.auth.urls')),
    
    # default route
    path('', views.tournaments_list, name='home')
]

tournois/tournaments/models.py
from collections import defaultdict
import random
from django.db import models
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.forms import ValidationError

import datetime
from django.db.models.signals import post_save


class Tournament(models.Model):

    """
    A tournament, with several pools, and teams
    """

    name = models.CharField(max_length=200)
    place = models.CharField(max_length=200, null=True)
    date = models.DateField('Date of the tournament', null = True)
    N_pools = models.IntegerField('Number of pools')
    N_teams_per_pools = models.IntegerField('Number of teams per pools')

    class Meta:
        db_table = "tournaments_tournoi"

    def __str__(self):
        return self.name    

class Team(models.Model):

    """
    A team, with several pools/matches
    """

    name = models.CharField(max_length=200)
    coach_name = models.CharField(max_length=200)
    team_members = models.CharField(max_length=2000)
    pool_points = models.IntegerField('Number of pool points', null=True)
    scored = models.IntegerField('Number of goals scored', null=True)
    conceded = models.IntegerField('Number of goals conceded', null=True)

    class Meta:
        db_table = "tournaments_equipe"

    def __str__(self):
        return self.name


class Pool(models.Model):

    """
    A pool, with one tournament, and several teams/matches
    """

    number = models.IntegerField('Number of the pool')
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    teams = models.ManyToManyField(Team)

    class Meta:
        db_table = "tournaments_poule"

    def __str__(self):
        return "Pool number " + str(self.number) + " : " + str(self.tournament)

    """
    A function that adds to the database all the matches possible in a pool
    """

    def all_matches(self):
        n = self.teams.all().count()
        list_all_matches = list(self.teams.all())
        for i in range(n - 1):
            for j in range(i + 1, n):
                random_score1 = random.randint(0, 7)
                random_score2 = random.randint(0, 7)
                match = Match(team1=list_all_matches[i],
                            team2=list_all_matches[j],
                            pool=self,
                            date=self.tournament.date,
                            hour="10h - 12h",
                            place=self.tournament.place,
                            score1=random_score1,
                            score2=random_score2)
                match.save()

    """
    A function that computes the ranking of the teams in a pool, 
    with the matches results

    :returns: a list with the teams ranked by pool points
    """

    def compute_ranking(self): 
        
        teams = self.teams.all()
        computed_pool_points = defaultdict(int)
        ranked_computed_teams = []

        for team in teams:
            team.pool_points = 0
            if team.scored is None:
                team.scored = 0
            if team.conceded is None : 
                team.conceded=0


            for match in Match.objects.filter(pool=self):
                match.team1.scored = 0
                match.team1.conceded = 0
                match.team2.scored = 0
                match.team2.conceded = 0

                if match.team1 == team:
                    team.scored += match.score1
                    team.conceded += match.score2

                    if match.score1 == match.score2:
                        team.pool_points += 1
                    elif match.score1 > match.score2:
                        team.pool_points += 3

                if match.team2 == team:
                    team.scored += match.score2
                    team.conceded += match.score1

                    if match.score1 == match.score2:
                        team.pool_points += 1
                    elif match.score2 > match.score1:
                        team.pool_points += 3

            computed_pool_points[team] = team.pool_points

        for k, v in sorted(computed_pool_points.items(), key=lambda x: -x[1]):
            ranked_computed_teams.append(k)

        return ranked_computed_teams

class Place(models.Model):
    name =  models.CharField(max_length=80)
    longitude = models.FloatField(null=False)
    latitude =  models.FloatField(null=False)
    def __str__(self):
        return self.name
    def script(self):
        return {"name": self.name, "latitude": self.latitude, "longitude": self.longitude}
        #return '[{"name":"' + str(self.name) + '", "latitude":"' + str(self.latitude) +'", "longitude":"'+str(self.longitude)+'"}]'
            
class Match(models.Model):

    """
    A match, several by pools, involving two teams
    """

    date = models.DateField('Date of the tournament', null = True)
    hour = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    team1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team1_set')
    score1 = models.IntegerField(default=0)
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team2_set')
    score2 = models.IntegerField(default=0)
    pool = models.ForeignKey(Pool, on_delete=models.CASCADE, blank=True, null= True)
    localisation = models.ForeignKey(Place, on_delete=models.SET_NULL, null=True)
    round = models.IntegerField(default=1)

    def __str__(self):
        return str(self.score1) + " " + str(self.team1) + " vs " + str(self.team2) + " " + str(self.score2)
    
    def winner(self):
        if self.score1 > self.score2:
            return self.team1
        elif self.score2 > self.score1:
            return self.team2
        else:
            return None
    
    #For future improvements     
    # def clean(self):
    #     super().clean()
    #     if self.score1 == self.score2:
    #         raise ValidationError("Les scores ne peuvent pas être égaux.")


class Comment(models.Model):

    """
    A comment, by one author, for one match
    """

    author = models.CharField(max_length=200)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Date & hour published', null=True)
    message = models.CharField(max_length=600)

    def __str__(self):
        return self.message
    

class FinalRound(models.Model):
    """
    A final round, with one tournament, and several matches
    """

    tournament = models.OneToOneField(Tournament, on_delete=models.CASCADE)
    matches = models.ManyToManyField(Match)  # Many-to-many relationship with Match
    rounds = models.IntegerField(default=1)  # Number of rounds completed so far

    class Meta:
        db_table = "tournaments_finalround"  # Name of the database table

    def __str__(self):
        return "Final Round for: " + str(self.tournament)  # String representation of the instance

    # Create pairings based on the pool ranking. The 1st of a pool must fight the 2nd of another random pool.
    def create_pairings(self):
        print("create_pairing called")
        pool_list = list(self.tournament.pool_set.all())  # Get all the pools for the tournament
        first_teams = []  # List of 1st ranked teams for each pool
        second_teams = []  # List of 2nd ranked teams for each pool

        for pool in pool_list:
            ranked_teams = pool.compute_ranking()  # Compute the ranking of teams for the pool
            first_teams.append(ranked_teams[0])  # Add the 1st ranked team to the first_teams list
            second_teams.append(ranked_teams[1])  # Add the 2nd ranked team to the second_teams list

        random.shuffle(second_teams)  # Shuffle the list of 2nd ranked teams

        for i in range(len(first_teams)):
            match = Match(
                team1=first_teams[i],
                team2=second_teams[i],
                pool=None,
                date=self.tournament.date,
                hour="10h - 12h",
                place=self.tournament.place,
            )
            match.save()  # Save the match to the database
            self.matches.add(match)  # Add the match to the matches many-to-many field
            # print(f"Match créé : {match.team1.name} vs {match.team2.name}")  --Debug

        self.save()  # Save the instance to the database
 
        
    #Useful for the template (since you can have 4, 8, 16, 32 teams)
    def get_total_matches(self):
        print("total matches called")
        pool_list = list(self.tournament.pool_set.all())
        return len(pool_list)
    
    #Helping create the next round match in finalround based on a list of winners from previous rounds
    @staticmethod
    def get_winners_from_previous_round(matches):
        winners = []
        # Print total number of matches
        print(f"Total matches: {len(matches)}") 
        for match in matches:
            # Print info for each match
            print(f"Checking winner for match {match.id}: {match.team1.name} ({match.score1}) vs {match.team2.name} ({match.score2})")
            winner = match.winner()
            if winner is not None:
                winners.append(winner)
                # Print info for winner found
                print(f"Winner found: {winner.name}")
            else:
                # Print info for no winner found
                print(f"No winner found for match {match.id}")
        # Print list of winners found
        print(f"Winners found: {winners}")
        return winners

    def get_next_round_matches(self):
        next_round_matches = []
        # Get list of completed matches
        completed_matches = [m for m in self.matches.all() if m.winner() is not None]
        if len(completed_matches) == self.matches.count():
            used_teams = []
            for match in self.matches.filter(round=self.rounds + 1):
                winner = match.winner()
                if winner and winner not in used_teams:
                    used_teams.append(winner)

tournois/tournaments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 1}), label='')
    class Meta:
        model = Comment
        fields = ['message']

class ResearchForm(forms.Form):
    research = forms.CharField(label="", max_length=100)
        
class ScoreForm(forms.Form):
    score1 = forms.IntegerField(min_value=0, label='Score 1')
    score2 = forms.IntegerField(min_value=0, label='Score 2')

tournois/tournaments/templates/tournaments/goals_per_match_plot.html
{% load static %}
<style>
    body {
      background-color: DE1E3D;
    }
  </style>
<!-- Add a canvas element for the bar chart -->
<canvas id="goals-per-match-plot"></canvas>

<!-- Include Chart.js library -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>

<script>

  const chart = {{chart_data|safe}};
    // Get data for the bar chart
  const labels = chart.labels;
  const totalGoals = chart.data;


  const goalData2 = {
    labels: labels,
    datasets: [{
      label: 'Buts dans le Match',
      data: totalGoals,
      backgroundColor: '#DE1E3D ',
      borderColor: '#DE1E3D ',
      borderWidth: 1,
      
      
    }]
  };

  // Set options for the bar chart
  const config2 = {
    type: 'bar',
    data: goalData2,
    options: {
        title: {
            display: true,
            text: 'Total de Buts par Match',
            fontColor: 'black', // set title font color to black
            fontSize: 20, // set title font size to 20
            fontWeight: 'bold' // set title font weight to bold
          },
          legend: {
            labels: {
              fontColor: 'black', // set legend font color to black

            }
          },    
      responsive: true,
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true,
            stepSize: 1,
            fontColor: 'black', // set font color to black
            fontSize: 16, // set font size to 16
            fontWeight: 'bold' // set font weight to bold
          }
        }],

        xAxes: [{
            ticks: {
              beginAtZero: true,
              stepSize: 1,
              fontColor: 'black', // set font color to black
              fontSize: 16, // set font size to 16
              fontWeight: 'bold' // set font weight to bold
            }
          }],
      },
      hover: {
        mode: null
      }
      
    }
  };

  // Create a new bar chart
  const goalChart2 = new Chart(
    document.getElementById('goals-per-match-plot'),
    config2
  );
</script>

tournois/tournaments/templates/tournaments/match_details.html
{% extends 'base.html'%}
{% load bootstrap5 %}
{% load static %}


{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}Match Details{% endblock title%}

{% block content %}

<div id="mapid" ></div>
{% if serialized_localisation%}
<script>
 var localisations = {{serialized_localisation | safe}}
</script>
{%endif%}
<script src="{% static 'tournaments/script.js' %}">
</script>

<!-- Barre de navigation -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        {% if username %}
            <a class="navbar-brand">Welcome <b>{{ username }}</b> !</a>
        {% endif %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tournaments:tournaments_list' %}">Tournament list</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tournaments:tournament_details' match.pool.tournament.id %}">{{ match.pool.tournament.name }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tournaments:pool_details' match.pool.id %}">Pool number {{ match.pool.number }}</a></li>
                <li class="nav-item"><a class="nav-link">Match : {{ match.score1 }} <b>{{ match.team1.name }}</b> VS <b>{{ match.team2.name }}</b> {{ match.score2 }}</a></li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if username %}
                <form action="{%url 'logout'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <li><button type="submit" class="btn btn-danger navbar-btn"><span class="glyphicon glyphicon-log-out"></span>Logout</button></li>
                </form>
            {% else %}
                <form action="{%url 'login'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <li><button type="submit" class="btn btn-danger navbar-btn"><span class="glyphicon glyphicon-log-in"></span>Login</button></li>
                </form>
            {% endif %}
        </ul>
    </div>
</nav>

<br> 

<!-- Détails du match sélectionné -->
<div class="row pb-3">
    <h1>Match : {{ match.score1 }} <b>{{ match.team1.name }}</b> VS <b>{{ match.team2.name }}</b> {{ match.score2 }}</h1> <br> 
</div>

<div class="row pb-3">
    <h3>
        <small>
            <ul>
                <li><b>Location</b> : {{ match.place }}</li> <br>
                <li><b>Date</b> : {{ match.date }}</li> <br>  
                <li><b>Hour</b> : {{ match.hour }}</li> <br>
            </ul>
        </small>
    </h3>
</div>

<!-- Liste des commentaires -->
<div class="row pb-3">
    <h1>Comments</h1>
</div>

<div class="row">
    {% if comment_ordered %}

        <table class="table table-striped">

            <thead>
            <tr>
                <th>Author</th>
                <th>Publication Date</th>
                <th>Comment</th>
                <th>Edit</th>
            </tr>
            </thead>

            <tbody>
                {% for comment in comment_ordered %}
                    <tr>
                        <td>{{ comment.author }}</td>
                        <td>{{ comment.pub_date }}</td>
                        <td>
                            <!-- Formulaire pour modifier un commentaire -->
                            {% if username|stringformat:"s" == comment.author and form and form.instance.id == comment.id %}
                                <form action="{% url 'tournaments:update_comment' match.id form.instance.id %}" method="POST" class="form">
                                    {% csrf_token %}
                                    {% bootstrap_form form %}

                                    {% buttons %}
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    {% endbuttons %}
                                </form>
                            {% else %}
                                {{ comment.message }}
                            {% endif %}
                        </td>
                        <td>
                            <!-- Boutons pour éditer les commentaires -->
                            {% if username|stringformat:"s" == comment.author %}
                                {% if not form or form.instance.id != comment.id %}
                                    <a class="btn btn-primary" href="{% url 'tournaments:update_comment' match.id comment.id %}">Edit</a>
                                {% endif %}
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>

    {% else %}
        <div class="jumbotron"><i>No comment yet for this match.</i></div>
    {% endif %}
</div>

<br> <br>

<!-- Formulaire pour modifier un commentaire -->
<div class="row">
    {% if username %}
        <form action="{% url 'tournaments:match_details' match.id %}" method="POST" class="form">
            {% csrf_token %}
            <label for="message"> Comment the match :</label>
            <input type="text" id="message" name="message"> <br/> <br/>

            {% buttons %}
              <button type="submit" class="btn btn-primary">Send</button>
            {% endbuttons %}
        </form>
    {% else %}
        <div class="jumbotron"><i>Please <a href="{% url 'login' %}"> login </a> to comment this match.</i></div>
    {% endif %}
</div>

{% endblock content %}

tournois/tournaments/templates/tournaments/match_details_finals.html
{% extends 'base.html'%}
{% load bootstrap5 %}

{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}Match Details{% endblock title%}

{% block content %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        {% if username %}
            <a class="navbar-brand">Welcome <b>{{ username }}</b> !</a>
        {% endif %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tournaments:tournaments_list' %}">Tournament list</a></li>
                <li class="nav-item"><a class="nav-link">Match : {{ match.score1 }} <b>{{ match.team1.name }}</b> VS <b>{{ match.team2.name }}</b> {{ match.score2 }}</a></li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if username %}
                <form action="{%url 'logout'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <li><button type="submit" class="btn btn-danger navbar-btn"><span class="glyphicon glyphicon-log-out"></span>Logout</button></li>
                </form>
            {% else %}
                <form action="{%url 'login'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <li><button type="submit" class="btn btn-danger navbar-btn"><span class="glyphicon glyphicon-log-in"></span>Login</button></li>
                </form>
            {% endif %}
        </ul>
    </div>
</nav>

<br> 

<div class="row pb-3">
    <h1>Match : {{ match.score1 }} <b>{{ match.team1.name }}</b> VS <b>{{ match.team2.name }}</b> {{ match.score2 }}</h1> <br> 
</div>

<div class="row pb-3">
    <h3>
        <small>
            <ul>
                <li><b>Location</b> : {{ match.place }}</li> <br>
                <li><b>Date</b> : {{ match.date }}</li> <br>  
                <li><b>Hour</b> : {{ match.hour }}</li> <br>
            </ul>
        </small>
    </h3>
</div>

<div class="row pb-3">
    <h1>Comments</h1>
</div>

<div class="row">
    {% if match.comment_set.all %}

        <table class="table table-striped">

            <thead>
            <tr>
                <th>Author</th>
                <th>Publication Date</th>
                <th>Comment</th>
                <th>Edit</th>
            </tr>
            </thead>

            <tbody>
                {% for comment in match.comment_set.all %}
                    <tr>
                        <td>{{ comment.author }}</td>
                        <td>{{ comment.pub_date }}</td>
                        <td>
                            {% if username|stringformat:"s" == comment.author and form and form.instance.id == comment.id %}
                                <form action="{% url 'tournaments:update_comment_finals' match.id form.instance.id %}" method="POST" class="form">
                                    {% csrf_token %}
                                    {% bootstrap_form form %}

                                    {% buttons %}
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    {% endbuttons %}
                                </form>
                            {% else %}
                                {{ comment.message }}
                            {% endif %}
                        </td>
                        <td>
                            {% if username|stringformat:"s" == comment.author %}
                                {% if not form or form.instance.id != comment.id %}
                                    <a class="btn btn-primary" href="{% url 'tournaments:update_comment_finals' match.id comment.id %}">Edit</a>
                                {% endif %}
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>

    {% else %}
        <div class="jumbotron"><i>No comment yet for this match.</i></div>
    {% endif %}
</div>

<br> <br>

<div class="row">
    {% if username %}
        <form action="{% url 'tournaments:match_details_finals' match.id %}" method="POST" class="form">
            {% csrf_token %}
            <label for="message"> Comment the match :</label>
            <input type="text" id="message" name="message"> <br/> <br/>

            {% buttons %}
              <button type="submit" class="btn btn-primary">Send</button>
            {% endbuttons %}
        </form>
    {% else %}
        <div class="jumbotron"><i>Please <a href="{% url 'login' %}"> login </a> to comment this match.</i></div>
    {% endif %}
</div>

{% endblock content %}

tournois/tournaments/templates/tournaments/pool_details.html
{% extends 'base.html'%}
{% load static %}

{% comment %}
Extend site-wide base HTML template located in main templates/ dir
(same level as manage.py)
{% endcomment %}

{% block title %}Pool Details{% endblock title%}

{% block content %}

<div id="mapid"></div>
<script >
    var localisations = {{serialized_localisation | safe}}
</script>
<script src="{% static 'tournaments/script.js' %}"></script>

<!-- Barre de navigation -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        {% if username %}
            <a class="navbar-brand">Welcome <b>{{ username }}</b> !</a>
        {% endif %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tournaments:tournaments_list' %}">Tournament list</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tournaments:tournament_details' pool.tournament.id %}">{{ pool.tournament.name }}</a></li>
                <li class="nav-item"><a class="nav-link">Pool number {{ pool.number }}</a></li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if username %}
                <form action="{%url 'logout'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <li><button type="submit" class="btn btn-danger navbar-btn"><span class="glyphicon glyphicon-log-out"></span>Logout</button></li>
                </form>
            {% else %}
                <form action="{%url 'login'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <li><button type="submit" class="btn btn-danger navbar-btn"><span class="glyphicon glyphicon-log-in"></span>Login</button></li>
                </form>
            {% endif %}
        </ul>
    </div>
</nav>

<br> 

{% if pool.match_set.all %}

    {% if user.is_authenticated and user.is_superuser %}
        <!-- Formulaire bouton pour reset les matchs de la poule -->
        <form method="POST" action="{% url 'tournaments:pool_details' pool.id %}">
            <input type="hidden" name="reset_matchs" value="true">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Reset matchs</button>
        </form>
    {% endif %}

    <div class="row"></div>
        <div class="row pb-3">
            <h1>Teams</h1>
        </div>

        <!-- Affichage des teams et des points de poule -->
        <table class="table table-striped">

            <thead>
            <tr>
                <th>Team</th>
                <th>Pool Points</th>
                <th>Scored</th>
                <th>Conceded</th>
            </tr>
            </thead>

            <tbody>
                {% for team in teams_ranked %}
                    <tr>
                        <td>{{ team.name }}</td>
                        <td>{{ team.pool_points }}</td>
                        <td>{{ team.scored }}</td>
                        <td>{{ team.conceded }}</td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>

        <div class="row pb-3">
            <br>
        </div>
    
        <div class="row pb-3">
            <h1>Matchs</h1>
        </div>

        <!-- Affichage des matchs de la poule -->
        <table class="table table-striped">

            <thead>
            <tr>
                <th>Match</th>
                <th>Location</th>
                <th>Date</th>
                <th>Hour</th>
            </tr>
            </thead>

            <tbody>
                {% for match in pool.match_set.all %}
                    <tr>
                        <td><a href="{% url 'tournaments:match_details' match.id %}">{{ match.score1 }} <b>{{ match.team1.name }}</b> VS <b>{{ match.team2.name }}</b> {{ match.score2 }}</a></td>
                        <td>{{ match.place }}</td>
                        <td>{{ match.date }}</td>
                        <td>{{ match.hour }}</td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>

        <style>
    
            #scatter-plot {
                max-width: 70%;
                margin: 0 auto;
                background-color: #acd4dc;
            }
            
            #goals-per-team-plot {
                max-width: 70%;
                margin: 0 auto;
                background-color: #acd4dc;
            }
            
            #goals-per-match-plot {
                max-width: 70%;
                margin: 0 auto;
                background-color: #acd4dc;
            }
        
        </style>
        
        <div class="row pb-3">
            <h1>Graphiques</h1>
        </div>
        
        
        <br>
        <br>
        <div>
            {% include 'tournaments/scatter_plot.html' %}
        </div>
        <br>
        <div>
            {% include 'tournaments/goals_per_team_plot.html' %}
        </div>
        <br>
        <br>
        <div>
            {% include 'tournaments/goals_per_match_plot.html' %}
        </div>
        <br>
        <br>



        
    </div>
{% else %}
    <div class="jumbotron"><i>No match in the pool.</i></div> <br>
    <!-- Bouton de calcul de tous les matchs possibles au sein d'une poule -->
    {% if user.is_authenticated and user.is_superuser %}
        <a class="btn btn-primary" href="{% url 'tournaments:compute_matches' pool.id 1 %}">Compute all matches possible</a>
    {% endif %}
{% endif %}



{% endblock content %}